name: Tests and release

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "precious-*"
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: ${{ matrix.platform.os_name }} with rust ${{ matrix.toolchain }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os_name: Linux-aarch64
            os: ubuntu-20.04
            target: aarch64-unknown-linux-musl
            bin: devpod-provider-hetzner-Linux-aarch64
            name: devpod-provider-hetzner-Linux-aarch64.tar.gz
          - os_name: Linux-x86_64
            os: ubuntu-20.04
            target:  x86_64-unknown-linux-gnu
            bin: devpod-provider-hetzner-Linux-x86_64
            name: devpod-provider-hetzner-Linux-x86_64.tar.gz

          - os_name: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: devpod-provider-hetzner-Windows-x86_64.exe
            name: devpod-provider-hetzner-Windows-x86_64.tar.gz

          - os_name: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: devpod-provider-hetzner-Darwin-x86_64
            name: devpod-provider-hetzner-Darwin-x86_64.tar.gz
          - os_name: macOS-aarch64
            os: macOS-latest
            target: aarch64-apple-darwin
            bin: devpod-provider-hetzner-Darwin-aarch64
            name: devpod-provider-hetzner-Darwin-aarch64.tar.gz
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v3
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: "build"
          target: ${{ matrix.platform.target }}
          toolchain: ${{ matrix.toolchain }}
          args: "--locked --release"
          strip: true
