name: Tests and release

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "precious-*"
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: ${{ matrix.platform.os_name }} with rust ${{ matrix.toolchain }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          #- os_name: Linux-aarch64
          #  os: ubuntu-20.04
          #  target: aarch64-unknown-linux-musl
          #  bin: devpod-provider-hetzner-linux-arm64
          - os_name: Linux-x86_64
            os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            bin: devpod-provider-hetzner-linux-amd64

          #- os_name: Windows-x86_64
          #  os: windows-latest
          #  target: x86_64-pc-windows-msvc
          #  bin: devpod-provider-hetzner-windows-amd64.exe

          #- os_name: macOS-x86_64
          #  os: macOS-latest
          #  target: x86_64-apple-darwin
          #  bin: devpod-provider-hetzner-darwin-amd64
          #- os_name: macOS-aarch64
          #  os: macOS-latest
          #  target: aarch64-apple-darwin
          #  bin: devpod-provider-hetzner-darwin-arm64
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v3
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: "build"
          target: ${{ matrix.platform.target }}
          toolchain: ${{ matrix.toolchain }}
          args: "--locked --release"
          strip: true
      - name: rename binary
        run: mv target/${{ matrix.platform.target }}/release/devpod-provider-hetzner target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}
      - name: Generate SHA-256
        run: shasum -a 256 target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }} | cut -d ' ' -f 1 > target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}.sha256
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}
      - name: Upload SHA-256
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}.sha256
  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Move binaries to release folder
        uses: actions/download-artifact@v3
        with:
          name: binaries
          path: release
      - name: Set up Go 1.20
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.x
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - id: get_version
        run: |
          RELEASE_VERSION=$(echo $GITHUB_REF | sed -nE 's!refs/tags/!!p')
          echo "::set-output name=release_version::$RELEASE_VERSION"
      - name: Compile binaries
        run: |
          chmod +x ./hack/build.sh
          ls -la
          ./hack/build.sh
        env:
          RELEASE_VERSION: ${{ steps.get_version.outputs.release_version }}
      - name: Save release assets
        uses: softprops/action-gh-release@v1
        with:
          files: release/*
